import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/provider/query-client-provider";
import AntdConfigProvider, {
  ThemeContext,
} from "@/provider/antd-config-provider";
import { ThemeProvider } from "@/provider/theme-provider";
import AntdRegistry from "@/provider/antd-registry";
import Navbar from "./component/layout/navbar";

import dynamic from "next/dynamic";
import { App } from "antd";

// const Navbar = dynamic(() => import('./component/layout/navbar'), { ssr: false })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning key="app-root">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <Navbar />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
